### PR TITLE
Fix bug #33 concerning picking in scrolled window

### PR DESCRIPTION
**Pull request by sebastien-schneider**
Actually my proposal to fix this bug is to update the wrapper element position on the onscroll event.

### CODE REVIEW

**Comment by sebastien-schneider** [comment]
I'm sorry actually it's not yet the right fix to my issue :-(

`top+window.scrollY` is a constant so that we don't have to set it on scroll event 

my issue, occurs only in production deployed environment, it's because the wrapper first position set value is not the right one when there is scrollbar on window. I don't know why.

The good thing in this fix is that when the user scroll the window, the wrapper position is set to the right value.

**Comment by sebastien-schneider** [comment]
This version fix my bug in production. I can't understand why the position value isn't set correctly during the requestAnimationFrame.

So I need to force position update in the onHold/onTouch and I use the getBoundingClientRect when checking the picking on node.

**Comment by sebastien-schneider** [comment]
Hi @WinterCore do you think you could review my PR and merge it if all is ok for you ?

Thank you

**Comment by WinterCore** [comment]
Resolves #33

**Comment by WinterCore** [comment]
Hey @sebastien-schneider, thank you so much for the PR. and I'm extremely sorry for the delay. It's just that I have been a bit busy lately.

**Pull request merged**
